initial work on requirements chapter
mqtt-varroa/varroa-documentation pull request #24
Opened 2019-03-11 14:26 UTC by YannickWeber

2019-03-11 15:01 UTC, RobinAtherton requested changes

2019-03-11 15:01 UTC, RobinAtherton commented on LaTeX/Parts/Chapter7.tex
> +In addition, it is indicated whether and how they are currently implemented.
```suggestion
Additionally it is indicated whether and how they are currently implemented.
```

2019-03-11 15:01 UTC, RobinAtherton commented on LaTeX/Parts/Chapter7.tex
> +This enables rich insight in the execution process of a Varroa test.
```suggestion
This enables a rich insight in the execution process of a Varroa test.
```
Don't know whether this is an improvement, but the sentence feels incomplete.

2019-03-11 15:01 UTC, RobinAtherton commented on LaTeX/Parts/Chapter7.tex
> +The fulfilment of this requirement is not verified yet.
This sentence feels very incomplete.

2019-03-11 15:01 UTC, RobinAtherton commented on LaTeX/Parts/Chapter7.tex
> +\emph{Varroa has to work in deterministic ways, meaning it should produce the same result for a Scenario every time.}
```suggestion
\emph{Varroa has to work in deterministic ways, meaning it should produce the same result for the same Scenario every time.}
```

2019-03-11 15:01 UTC, RobinAtherton commented on LaTeX/Parts/Chapter7.tex
> +To ensure this determinism several measures are taken in the distribution and execution of a Scenario (see chapter \ref{sec:Architecture}).
```suggestion
To guarantee this determinism several measures are taken, ensuring deterministic distribution and execution of a Scenario (see chapter \ref{sec:Architecture}).
```
Not sure about the semicolon.

2019-03-11 15:01 UTC, RobinAtherton commented on LaTeX/Parts/Chapter7.tex
> +Varroa is organized as a distributed System, it is composed of a Commander and multiple Agents that can run on different machines.
```suggestion
Varroa is organized as a distributed System.
It is composed of a Commander and multiple Agents.
These components can be run on separate machines. 
```

2019-03-11 15:01 UTC, RobinAtherton commented on LaTeX/Parts/Chapter7.tex
> +To ensure high code quality several measures are taken.
```suggestion
To ensure the high code quality standards, several measures were taken.
```
Sentence still is pretty generic, we should have a further look at this.

2019-03-11 15:01 UTC, RobinAtherton commented on LaTeX/Parts/Chapter7.tex
> +For example the consequent use of nullability annotiations and a broad test code coverage.
```suggestion
An example for these measures is the consequent use of nullability as well as broad test code coverage. 
```

2019-03-11 15:01 UTC, RobinAtherton commented on LaTeX/Parts/Chapter7.tex
> +By the use of integration tests and general unit tests stability is ensured.
```suggestion
Stability is ensured by the use of integration tests and general unit tests.
```

2019-03-11 15:01 UTC, RobinAtherton commented on LaTeX/Parts/Chapter7.tex
> +This requirement is fulfilled. This documentation educates the user on defining a custom scenario and after that executing it on his Varroa Distributed System (\ref{sec:ScenarioConcept} and \ref{sec:
```suggestion
This requirement is fulfilled. 
The documentation educates the user on the definition of a custom scenario aswell as the exectution of it on her Varroa Distributed System (\ref{sec:ScenarioConcept} and \ref{sec:Execution}).
```
Georg said we gender everything feminine.

2019-03-12 07:52 UTC, YannickWeber commented on LaTeX/Parts/Chapter7.tex
> +The fulfilment of this requirement is not verified yet.
It just says that we could not verify this yet. It is okay imho.

2019-03-12 07:54 UTC, YannickWeber commented on LaTeX/Parts/Chapter7.tex
> +To ensure high code quality several measures are taken.
Because of this there are the following sentences.

2019-03-12 07:58 UTC, AcidSepp commented on LaTeX/Parts/Chapter7.tex
> +This requirement is fulfilled. This documentation educates the user on defining a custom scenario and after that executing it on his Varroa Distributed System (\ref{sec:ScenarioConcept} and \ref{sec:
```suggestion
This requirement is fulfilled.
The documentation educates the user on the definition of a custom scenario aswell as the exectution of it on his Varroa Distributed System (\ref{sec:ScenarioConcept} and \ref{sec:Execution}).
```

2019-03-12 08:00 UTC, merged